# -*- coding: utf-8 -*-
"""NLP TASK 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jI56UUx6V6rjuVXXB-0Dl_XVUTFjWtyM
"""

import re

# 1. Match 'abc' at the start of string
pattern1 = re.compile(r'abc')
result1 = pattern1.match('abcdef')
if result1:
    print("Match found:", result1.group())

# 2. Match any single character (except newline)
pattern2 = re.compile(r'.')
result2 = pattern2.search('Hello')
if result2:
    print("Character found:", result2.group())

# 3. Match any vowel character
pattern3 = re.compile(r'[aeiou]')
result3 = pattern3.search('Hello')
if result3:
    print("Vowel found:", result3.group())

# 4. Match Social Security Number pattern: 3 digits-2 digits-4 digits
pattern4 = re.compile(r'\d{3}-\d{2}-\d{4}')
result4 = pattern4.match('123-45-6789')
if result4:
    print("Social Security Number:", result4.group())

# 5. Match a literal dot '.'
pattern5 = re.compile(r'\.')
result5 = pattern5.search('www.example.com')
if result5:
    print("Dot found:", result5.group())

# 6. Extract date components (day/month/year)
pattern6 = re.compile(r'(\d{2})/(\d{2})/(\d{4})')
result6 = pattern6.match('01/09/2024')
if result6:
    print("Day:", result6.group(1))
    print("Month:", result6.group(2))
    print("Year:", result6.group(3))

# 7. Match either "cat" or "dog"
pattern7 = re.compile(r'cat|dog')
result7 = pattern7.search('I have a cat and a dog')
if result7:
    print("Animal found:", result7.group())
